### ISSUE TITLE
Parallelize CI Build?

### ISSUE THREAD

**Issue by DavePearce** [ConsenSys/evm-dafny#506]
Basically just testing whether a parallel build makes any difference.

**Comment by DavePearce** [comment]
Yes, outcome is that they do indeed run in parallel.  The test workflow file was:

```yaml
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "3.10.0"

      - name: Z3 version
        continue-on-error: true
        run: $HOME/dafny/z3/bin/z3 --version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle Build
        run: gradle build

  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "3.10.0"

      - name: Z3 version
        continue-on-error: true
        run: $HOME/dafny/z3/bin/z3 --version

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build with the Makefile
        run: make ci
```
